name: SSH
on:
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'
jobs:

  build:
    name: Deploy on VPS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run build

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          registry: registry.maxencemottard.com
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build latest Docker image
        run: docker build . --tag  registry.maxencemottard.com/maxmottard/stocks-core:latest

      - name: Push latest Docker image
        run: docker push registry.maxencemottard.com/maxmottard/stocks-core:latest

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            docker rm -f stocks_core || true;
            docker pull registry.maxencemottard.com/maxmottard/stocks-core:latest;
            docker run --detach \
              --name stocks_core \
              --network reverse-proxy \
              --env-file .env.stocks \
              --restart always \
              -l traefik.enable=true \
              -l traefik.http.routers.STOCKS_API.rule=Host\(\`stocks.maxencemottard.com\`\) \
              -l traefik.http.routers.STOCKS_API.entrypoints=http \
              -l traefik.http.routers.STOCKS_API.middlewares=https-redirect@file \
              -l traefik.http.routers.STOCKS_API-Https.rule=Host\(\`stocks.maxencemottard.com\`\) \
              -l traefik.http.routers.STOCKS_API-Https.entrypoints=https \
              -l traefik.http.routers.STOCKS_API-Https.middlewares=security@file\,compression@file \
              -l traefik.http.routers.STOCKS_API-Https.tls=true \
              -l traefik.http.routers.STOCKS_API-Https.tls.certresolver=letsencrypt \
              registry.maxencemottard.com/maxmottard/stocks-core:latest;
